FROM python:3.11-slim

RUN pip install streamlit streamlit-chat langchain langchain-community langsmith langchain-openai langchain-ollama langchain-huggingface faiss-cpu pypdf python-dotenv langid sentence-transformers

CMD ["streamlit", "run", "rag/main.py"]
